import os


CHUNK_COLLECTION = os.getenv("QDRANT_CHUNK_COLLECTION", "medical_chunks")
ENTITY_COLLECTION = os.getenv("QDRANT_ENTITY_COLLECTION", "medical_entities")
RELATION_COLLECTION = os.getenv("QDRANT_RELATION_COLLECTION", "medical_relations")


ALL_COLLECTIONS = [
    CHUNK_COLLECTION,
    ENTITY_COLLECTION,
    RELATION_COLLECTION,
]